
# Automagically generated by Approximatrix Simply Fortran
#
FC=gfortran
CC=gcc
RM=rm

IDIR=
# -I error: Directory C:/Program Files (x86)/Simply Fortran/mingw-w64/include/ does not exist
# -I error: Directory C:/Users/sukhveersanghera/Desktop/Gas Turbine Project/CCMD/Default Add-On Include Directory does not exist

LDIR=
# -L error: Directory C:/Users/sukhveersanghera/Desktop/Gas Turbine Project/CCMD/Default Add-On Directory does not exist


SPECIALFLAGS=-g $(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS=
PRJ_CFLAGS=
PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS)  $(PRJ_FFLAGS) #-Jmodules

CFLAGS=-g  $(IDIR) $(PRJ_CFLAGS)

all: CCMD

build/CORE_MLT.o: ./Subroutines/CORE_MLT.FOR
	$(FC) -c -o build/CORE_MLT.o $(FFLAGS) ./Subroutines/CORE_MLT.FOR

build/CORE_PH0.o: ./Subroutines/CORE_PH0.FOR
	$(FC) -c -o build/CORE_PH0.o $(FFLAGS) ./Subroutines/CORE_PH0.FOR

build/CORE_PR.o: ./Subroutines/CORE_PR.FOR
	$(FC) -c -o build/CORE_PR.o $(FFLAGS) ./Subroutines/CORE_PR.FOR

build/CORE_QUI.o: ./Subroutines/CORE_QUI.FOR
	$(FC) -c -o build/CORE_QUI.o $(FFLAGS) ./Subroutines/CORE_QUI.FOR

build/CORE_STN.o: ./Subroutines/CORE_STN.FOR
	$(FC) -c -o build/CORE_STN.o $(FFLAGS) ./Subroutines/CORE_STN.FOR

build/FLASH2.o: ./Subroutines/FLASH2.FOR
	$(FC) -c -o build/FLASH2.o $(FFLAGS) ./Subroutines/FLASH2.FOR

build/FLSH_SUB.o: ./Subroutines/FLSH_SUB.FOR
	$(FC) -c -o build/FLSH_SUB.o $(FFLAGS) ./Subroutines/FLSH_SUB.FOR

build/IDEALGAS.o: ./Subroutines/IDEALGAS.FOR
	$(FC) -c -o build/IDEALGAS.o $(FFLAGS) ./Subroutines/IDEALGAS.FOR

build/MIX_AGA8.o: ./Subroutines/MIX_AGA8.FOR
	$(FC) -c -o build/MIX_AGA8.o $(FFLAGS) ./Subroutines/MIX_AGA8.FOR

build/MIX_HMX.o: ./Subroutines/MIX_HMX.FOR
	$(FC) -c -o build/MIX_HMX.o $(FFLAGS) ./Subroutines/MIX_HMX.FOR

build/PROP_SUB.o: ./Subroutines/PROP_SUB.FOR
	$(FC) -c -o build/PROP_SUB.o $(FFLAGS) ./Subroutines/PROP_SUB.FOR

build/REALGAS.o: ./Subroutines/REALGAS.FOR
	$(FC) -c -o build/REALGAS.o $(FFLAGS) ./Subroutines/REALGAS.FOR

build/SAT_SUB.o: ./Subroutines/SAT_SUB.FOR
	$(FC) -c -o build/SAT_SUB.o $(FFLAGS) ./Subroutines/SAT_SUB.FOR

build/SETUP.o: ./Subroutines/SETUP.FOR
	$(FC) -c -o build/SETUP.o $(FFLAGS) ./Subroutines/SETUP.FOR

build/SETUP2.o: ./Subroutines/SETUP2.FOR
	$(FC) -c -o build/SETUP2.o $(FFLAGS) ./Subroutines/SETUP2.FOR

build/TRNS_ECS.o: ./Subroutines/TRNS_ECS.FOR
	$(FC) -c -o build/TRNS_ECS.o $(FFLAGS) ./Subroutines/TRNS_ECS.FOR

build/TRNS_TCX.o: ./Subroutines/TRNS_TCX.FOR
	$(FC) -c -o build/TRNS_TCX.o $(FFLAGS) ./Subroutines/TRNS_TCX.FOR

build/TRNS_VIS.o: ./Subroutines/TRNS_VIS.FOR
	$(FC) -c -o build/TRNS_VIS.o $(FFLAGS) ./Subroutines/TRNS_VIS.FOR

build/TRNSP.o: ./Subroutines/TRNSP.FOR
	$(FC) -c -o build/TRNSP.o $(FFLAGS) ./Subroutines/TRNSP.FOR

build/UTILITY.o: ./Subroutines/UTILITY.FOR
	$(FC) -c -o build/UTILITY.o $(FFLAGS) ./Subroutines/UTILITY.FOR

build/CORE_ANC.o: ./Subroutines/CORE_ANC.FOR
	$(FC) -c -o build/CORE_ANC.o $(FFLAGS) ./Subroutines/CORE_ANC.FOR

build/CORE_BWR.o: ./Subroutines/CORE_BWR.FOR
	$(FC) -c -o build/CORE_BWR.o $(FFLAGS) ./Subroutines/CORE_BWR.FOR

build/CORE_CPP.o: ./Subroutines/CORE_CPP.FOR
	$(FC) -c -o build/CORE_CPP.o $(FFLAGS) ./Subroutines/CORE_CPP.FOR

build/CORE_DE.o: ./Subroutines/CORE_DE.FOR
	$(FC) -c -o build/CORE_DE.o $(FFLAGS) ./Subroutines/CORE_DE.FOR

build/CORE_ECS.o: ./Subroutines/CORE_ECS.FOR
	$(FC) -c -o build/CORE_ECS.o $(FFLAGS) ./Subroutines/CORE_ECS.FOR

build/CORE_FEQ.o: ./Subroutines/CORE_FEQ.FOR
	$(FC) -c -o build/CORE_FEQ.o $(FFLAGS) ./Subroutines/CORE_FEQ.FOR

build/CCMD.o: CCMD.F90
	$(FC) -c -o build/CCMD.o $(FFLAGS) ./CCMD.F90

clean:
	$(RM) build/CORE_MLT.o
	$(RM) build/CORE_PH0.o
	$(RM) build/CORE_PR.o
	$(RM) build/CORE_QUI.o
	$(RM) build/CORE_STN.o
	$(RM) build/FLASH2.o
	$(RM) build/FLSH_SUB.o
	$(RM) build/IDEALGAS.o
	$(RM) build/MIX_AGA8.o
	$(RM) build/MIX_HMX.o
	$(RM) build/PROP_SUB.o
	$(RM) build/REALGAS.o
	$(RM) build/SAT_SUB.o
	$(RM) build/SETUP.o
	$(RM) build/SETUP2.o
	$(RM) build/TRNS_ECS.o
	$(RM) build/TRNS_TCX.o
	$(RM) build/TRNS_VIS.o
	$(RM) build/TRNSP.o
	$(RM) build/UTILITY.o
	$(RM) build/CORE_ANC.o
	$(RM) build/CORE_BWR.o
	$(RM) build/CORE_CPP.o
	$(RM) build/CORE_DE.o
	$(RM) build/CORE_ECS.o
	$(RM) build/CORE_FEQ.o
	$(RM) build/CCMD.o
	$(RM) build/COMTRN.o
	$(RM) build/COMMONS.o
	$(RM) build/PASS_FTN.o
	$(RM) CCMD

CCMD:  build/CORE_MLT.o build/CORE_PH0.o build/CORE_PR.o build/CORE_QUI.o build/CORE_STN.o build/FLASH2.o build/FLSH_SUB.o build/IDEALGAS.o build/MIX_AGA8.o build/MIX_HMX.o build/PROP_SUB.o build/REALGAS.o build/SAT_SUB.o build/SETUP.o build/SETUP2.o build/TRNS_ECS.o build/TRNS_TCX.o build/TRNS_VIS.o build/TRNSP.o build/UTILITY.o build/CORE_ANC.o build/CORE_BWR.o build/CORE_CPP.o build/CORE_DE.o build/CORE_ECS.o build/CORE_FEQ.o build/CCMD.o
	$(FC) -o CCMD -static build/CORE_MLT.o build/CORE_PH0.o build/CORE_PR.o build/CORE_QUI.o build/CORE_STN.o build/FLASH2.o build/FLSH_SUB.o build/IDEALGAS.o build/MIX_AGA8.o build/MIX_HMX.o build/PROP_SUB.o build/REALGAS.o build/SAT_SUB.o build/SETUP.o build/SETUP2.o build/TRNS_ECS.o build/TRNS_TCX.o build/TRNS_VIS.o build/TRNSP.o build/UTILITY.o build/CORE_ANC.o build/CORE_BWR.o build/CORE_CPP.o build/CORE_DE.o build/CORE_ECS.o build/CORE_FEQ.o build/CCMD.o $(LDIR) $(PRJ_LFLAGS)


